# Generated by Django 5.0.3 on 2024-03-06 14:01

import StorageMgmtServ.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.FloatField(default=StorageMgmtServ.models.get_timestamp, editable=False)),
                ('file', models.FileField(upload_to='taskFiles/')),
                ('name', models.TextField()),
                ('size', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
