# Generated by Django 5.0.3 on 2024-03-06 19:59

import StorageMgmtServ.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageMgmtServ', '0002_alter_storagefile_created_by_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='created_on',
            field=models.FloatField(default=StorageMgmtServ.models.get_timestamp, editable=False),
        ),
    ]
