# Generated by Django 5.0.3 on 2024-03-11 15:46

import StorageMgmtServ.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StorageMgmtServ', '0004_alter_folder_created_by_alter_storagefile_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagefile',
            name='modified_on',
            field=models.FloatField(default=StorageMgmtServ.models.get_timestamp, editable=False),
        ),
    ]
